apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend-service
  name: my-service-frontend
spec:
  selector:
    app: udagram-frontend
  ports:
    - name: "2310"
      protocol: TCP
      port: 80
      targetPort: 2310
